### ISSUE TITLE
docs: document installation procedure

### ISSUE THREAD

**Issue by wardi** [datacats/ckan-multisite#5]
Assuming a Debian/Ubuntu machine first. Include a script that can be pasted one command at a time with minimal interaction.

**Comment by wardi** [comment]
@JackMc We're pretty close to this right now, maybe just add the venv setup to the readme

**Comment by JackMc** [comment]
Okay, just say like `do virtualenv ~/ckan-multisite` or something?

**Comment by wardi** [comment]
yeah, just include instructions that could be copy-pasted into a plain ubuntu vm as a normal user with sudo access to get up and running

**Comment by deniszgonjanin** [comment]
This area could use some more work. Setting up on a plain Ubuntu 14.04 machine, I ran into a few problems that would be quite annoying for the average user. Things like needing a non-root user to install datacats, creating a virtualenv to avoid other hassles, getting docker running easily, installing uwsgi, and running the run.sh script in prod mode.

Since this is targeted for the initial release - instead of doing a lot of documentation work, thebest thing to do might be a 5-10 min screencast of explaining what the project is, followed by installation on a fresh Ubuntu machine running on AWS or digital ocean, followed by a demo of the CKAN site(s) up and running.

**Comment by deniszgonjanin** [comment]
The screencast can be totally improvised with no editing. It's a first release, after all

**Comment by JackMc** [comment]
So for this now we have the run.sh script which assumes a debian computer and prompts the user to do an automatic installation. Does this satisfy this requirement?

**Comment by deniszgonjanin** [comment]
Yes, especially for the MVP I think this works perfectly
